name: Synth

on:
  push:
    branches:
      - main

jobs:
  main:

    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'yarn'
    - run: yarn install --frozen-lockfile
    - run: yarn build
    - uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::503479554940:role/RG-Systems-GH-Actions
        role-session-name: vp-cdk-deploy
        aws-region: us-east-1
    - run: yarn cdk synth
